name: rgb_controller_app
description: "ESP32 RGB LED Strip Controller with Music Reactive Mode and 256 Custom Pattern Steps"
homepage: https://github.com/your-username/rgb-controller-app
repository: https://github.com/your-username/rgb-controller-app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  syncfusion_flutter_sliders: ^23.1.36
  
  # Networking
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  
  # State Management
  provider: ^6.0.5
  
  # Utilities
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true